### ISSUE TITLE
FSCrawler is not running

### ISSUE THREAD

**Issue by My-project-repository** [dadoonet/fscrawler#1089]
Hello, I'm new on FSCrawler and ES

When I create a job inside cutom repository it doesn't appear inside existing job list (bin/fscrawler)

After changing the _settings.yaml and rerun the job nothing happen and there's no index in ES

![image](https://user-images.githubusercontent.com/50357357/106271389-80025e80-6240-11eb-8671-e9adda012d67.png)
![image](https://user-images.githubusercontent.com/50357357/106271418-8c86b700-6240-11eb-9e41-bf226f226aa8.png)

**Comment by dadoonet** [comment]
Could you avoid using images for code and instead paste the content in the issue?
Which version are you using ?

is there anything in logs?

**Comment by mri-nicolas** [comment]
I think I actually have the same bug, I spend quite some time trying to figure out the reason, installing version 2.7 also on the 2.6 docker..

Eventually downgrading to 2.6 and elastic 6 worked, however I am trying to use Elasticsearch 7

Basically absolutely nothing happens when running fscrawler.. The exact same command works successfully on version 2.6

**Comment by dadoonet** [comment]
If you are using ES7, you need to download the distribution for ES7: `fscrawler-es7-2.7-SNAPSHOT`

Could you try it?

Also start fscrawler with `--debug` so we will know more hopefully.

**Comment by dadoonet** [comment]
No more details on this. I'm closing but feel free to add more comments and logs if you have that.
