### ISSUE TITLE
job name use an alias

### ISSUE THREAD

**Issue by momocg** [dadoonet/fscrawler#1091]
**Describe the bug**

when I start fscrawler with job name configured as an alias ,it can not be started.

example cmd: bin/fscrawler index_alias --loop 0 --rest

**Logs**

```
we can not start Elasticsearch Client. Exiting. [type=invalid_index_name_exception, reason=Invalid index name, already exists as alias]
```

**Versions:**
 - OS: [suse]
 - Version [fscrawler-es7-2.7-snapshot]

**Comment by dadoonet** [comment]
How did you create the index/alias?

**Comment by momocg** [comment]
> How did you create the index/alias?

Created in advance with the PUT command

**Comment by dadoonet** [comment]
> Created in advance with the PUT command

That's why it's probably failing. If you did not use the right mapping, then it fails... See

* https://fscrawler.readthedocs.io/en/latest/admin/fs/elasticsearch.html#mappings
* https://fscrawler.readthedocs.io/en/latest/admin/fs/elasticsearch.html#creating-your-own-mapping-analyzers

If you don't need to add any specifics, just delete the index with the `DELETE` command and run again FSCrawler. It will create the right index for you.
