### ISSUE TITLE
Examples not base64 but MD5

### ISSUE THREAD

**Issue by j0hnsmith** [dadoonet/fscrawler#115]
In the readme the example document includes

     "path":{
        "encoded":"bceb3913f6d793e915beb70a4735592",
        "root":"bceb3913f6d793e915beb70a4735592",
        "virtual":"",
        "real":"/tmp/testfs_metadata/test.odt"
     },

It says that `path.encoded` and `path.root` is base64 yet those values aren't base64. I'm curious what the process is to turn `/tmp/testfs_metadata/test.odt` into `bceb3913f6d793e915beb70a4735592`.

**Comment by dadoonet** [comment]
You're right. The documentation is incorrect. It's a MD5 signature. https://github.com/dadoonet/fsriver/blob/master/src/main/java/fr/pilato/elasticsearch/river/fs/river/SignTool.java#L34

I probably won't fix the doc because this plugin is now stopped as elasticsearch 2.0 does not support anymore rivers.

**Comment by j0hnsmith** [comment]
Fair enough, thanks for quick response.

**Comment by dadoonet** [comment]
I ended up fixing the documentation. Thanks for reporting this!
