### ISSUE TITLE
Performance of reindexing

### ISSUE THREAD

**Issue by ThaDafinser** [dadoonet/fscrawler#247]
Hello,

first off - very nice tool :smile: 
I've played around today a bit with this crawler (combined with Tika + OCR tesseract).

The initial indexing of 1,5GB (8.000 files) took a while - which is fine of course.

My main problem is currently, that the "reindexing" takes more time then i thought.
For those 8.000 files it took about 2 minutes.

Is there any possibility to speed up that part? Configuration or similar?

Does it currently compare the file `modification` timestamp with the `lastrun` timestamp? Or is it another approach?

Thanks in advance for any information :+1:

**Comment by dadoonet** [comment]
Thanks!

FS Crawler is supposed to index only modified documents since the last time it runs.
If it does not work as this, then it's a bug.

I never played with OCR actually so I have no idea on how it plays a role here.

That being said, you said that you injected on the first run quicker than on the second run, right?
If all documents are updated (due to a bug or because they have been updated or because FS Crawler `_status.json` has been removed/modified manually), then it's "normal" that it takes more time than the first run.

Update has always a cost in elasticsearch.

Have a look at your logs in elasticsearch and make sure you are not running low on memory (GC messages in logs for example).

May be increase the `bulk_size` to `1000` and see how it goes. I put the default very low because of potentially big files which can consume lot of memory. But may be increasing that can come with a gain.
Also the default value `5s` is may be too low. `10s` or `15s` could be fine.

I think I should change the default `bulk_size` to something related with the heap size allocated to FS Crawler. And may be this `bulk_size` should be a `bulk_size_in_mb` instead...

I'm curious about your findings if you turn a bit the knobs. Can you update this thread with your findings?

Thanks!

**Comment by ThaDafinser** [comment]
Thanks for your excellent explanation. How does the program actually check for changes?
If i understand the code correctly, it uses a selfmade hash? https://github.com/dadoonet/fscrawler/blob/8feb196a2363955fabfa225afb862e065701a119/src/main/java/fr/pilato/elasticsearch/crawler/fs/meta/doc/File.java#L130-L140

The initial indexing took way longer then the two minutes to check for updates, that is okay for me.
Two minutes were required without a real change (i just executed again the crawler again, without any document change)

My target would be to index 2TB of data :fearful: : 
So with a quick calculation, the update check would need 44h to check for all files again.
(of course this would be lowered by some factors, lets say 5 ... would still require ~9h for one run)

Since the data is managed on NetApp, i will try to see if i can do something with the FPolicy to track the changes... https://library.netapp.com/ecmdocs/ECMP1401220/html/GUID-F7C6F79C-D4EC-4321-9A31-B8DFF7D97128.html

Maybe that would be a better solution, or something completely different.

I will try to keep you updated.

**Comment by dadoonet** [comment]
> If i understand the code correctly, it uses a selfmade hash? 

Yes. And I'm not happy with that part of the code.
I know that on some systems like Unix I could use something based on iNodes to be much more efficient but then come the Windows portability problem I guess.

I started to play with RSync and see if I can simply remove all the crawling part with a simple RSync server in FSCrawler when launched as a server and a RSync client when launched as an agent.
That's something I have in mind but never found enough free time to really implement this yet.

**Comment by ThaDafinser** [comment]
Some ideas releated to this topic.
- split the metadata + content extraction similar to `tika-server` - Just provide an REST/HTTP API for it.
- this would have the benefit, that you can create a custom crawler (or switch), but still use the same index and indexing mechanism

With this split, it's possible to create a general crawler for all systems and specialized ones for unix/windows.

**Comment by dadoonet** [comment]
@ThaDafinser For the record, I pushed #261 which now adds a REST Layer.

Is that what you were expecting? Can we close your issue?

**Comment by ThaDafinser** [comment]
@dadoonet awesome! :+1: 
I will get into this topic next week again and will try it out.

Thanks for the effort!

**Comment by ThaDafinser** [comment]
@dadoonet i could not find the docs to add a parameter to choose the target index/type
https://github.com/dadoonet/fscrawler#starting-with-a-rest-gateway

But i see you are grabbing it from a setting
https://github.com/dadoonet/fscrawler/blob/cfde2a1edfa0ca71a03496df2cf822d12d65c021/src/main/java/fr/pilato/elasticsearch/crawler/fs/rest/UploadApi.java#L110

Is it possible to set the parameter in the url? Somehow like here?
```
curl -F "file=@test.txt" "http://127.0.0.1:8080/fscrawler/_upload?index=my_index&type=my_type"
```

**Comment by dadoonet** [comment]
Not for now. So basically you would like to be able to read any parameter either from settings or from the command line.

That makes sense to me. Can you open an issue for that?
