### ISSUE TITLE
access fscrawler by IP and port

### ISSUE THREAD

**Issue by hailisun** [dadoonet/fscrawler#441]
May I install fscrawler on server and access its interface by server's ip like : 192.168.2.1:8080/_upload?

**Comment by dadoonet** [comment]
That's the goal of the rest endpoint I added.

Is it not working ?

**Comment by hailisun** [comment]
Yeah! I start  fscrawler on server, when I access it by  "curl -F 'file=@/home/andin/testFscrawler' '127.0.0.1:8180/fscrawler/_upload' ",  it works well. But  "curl -F 'file=@/home/andin/testFscrawler' '192.168.15.4:8180/fscrawler/_upload' "  will print an error like ' curl: (7) Failed to connect to 192.168.15.4 port 8180: Connection refused '

What should I do to solve this question,  please?

**Comment by dadoonet** [comment]
I believe you need to change rest.host attribute. It defaults to 127.0.0.1

**Comment by hailisun** [comment]
Yes. I got it ! 

Thank you very much!

**Comment by MoKmaal** [comment]
I can open 127.0.0.1:8080/fscrawler using my web browser
but when trying to test connection or upload file using terminal, it print an error 
curl: (7) Failed to connect to 127.0.0.1 port 8888: Connection refused

What should I do to solve this question, please?

**Comment by shadiakiki1986** [comment]
Why are you publishing to the port 8888 as it seems in your error log?
Fscrawler is at port 8080 not 8888

**Comment by MoKmaal** [comment]
Kindly, I want to know from where could I change this configuration of the port 8888 I couldn't find any conf files in FSCrawler after installation

**Comment by shadiakiki1986** [comment]
What's the command you're using to send the file to fscrawler from the
terminal?

**Comment by MoKmaal** [comment]
curl -F "file=@documents.txt" "http://127.0.0.1:8080/fscrawler/_upload"

**Comment by shadiakiki1986** [comment]
Could you send the same command with the error showing underneath it upon
execution?

**Comment by MoKmaal** [comment]
[
Start Connect
![screenshot from 2018-01-31 11-45-42](https://user-images.githubusercontent.com/18743451/35616056-b2ccdcbe-067c-11e8-8f30-7d9439f63f25.png)

upload
![screenshot from 2018-01-31 11-45-20](https://user-images.githubusercontent.com/18743451/35616060-b5492baa-067c-11e8-9c6a-39bbeb972980.png)

](url)

**Comment by dadoonet** [comment]
But you said it's running on port 8080.
Why do you send your request to port 8888?

**Comment by shadiakiki1986** [comment]
First of all, you're missing the --rest flag.
The fscrawler command should be
`./fscrawler legal_test --loop 0 --rest`

Second of all, is it possible that you have some sort of port redirection
happening from 8080 to 8888?

**Comment by MoKmaal** [comment]
My Steps:
1. run ./elasticsearch in terminal
2. run ./fscrawler test --loop 0 --rest   in another terminal window
3. trying to check connection on web browser and it shows to me and it works
4. but if i run 
curl -F "file=@documents.txt" "http://127.0.0.1:8080/fscrawler/_upload"
or
curl http://127.0.0.1:8080/fscrawler/

in terminal it gives me 
 curl: (7) Failed to connect to 127.0.0.1 port 8888: Connection refused

I don't know from where it redirect to port 8888
could you help me, please?
thanks in advance

**Comment by shadiakiki1986** [comment]
How do you check in the web browser?

**Comment by dadoonet** [comment]
@MoKmaal could you run:

```sh
./fscrawler test --loop 0 --rest --debug
```

And paste the results here? Raw logs please, not a screenshot.

**Comment by MoKmaal** [comment]
mkamal@mkamal-Inspiron-5559:~/fscrawler-2.4/bin$ ./fscrawler legal_test --loop 0 --rest --debug
09:44:45,186 DEBUG [f.p.e.c.f.u.FsCrawlerUtil] Mapping [2/_settings.json] already exists
09:44:45,187 DEBUG [f.p.e.c.f.u.FsCrawlerUtil] Mapping [2/_settings_folder.json] already exists
09:44:45,187 DEBUG [f.p.e.c.f.u.FsCrawlerUtil] Mapping [5/_settings.json] already exists
09:44:45,188 DEBUG [f.p.e.c.f.u.FsCrawlerUtil] Mapping [5/_settings_folder.json] already exists
09:44:45,188 DEBUG [f.p.e.c.f.u.FsCrawlerUtil] Mapping [6/_settings.json] already exists
09:44:45,188 DEBUG [f.p.e.c.f.u.FsCrawlerUtil] Mapping [6/_settings_folder.json] already exists
09:44:45,189 DEBUG [f.p.e.c.f.FsCrawler] Starting job [legal_test]...
09:44:45,674 DEBUG [f.p.e.c.f.c.ElasticsearchClient] Using elasticsearch >= 5, so we can use ingest node feature
09:44:45,738 WARN  [f.p.e.c.f.FsCrawler] We found old configuration index settings in [/home/mkamal/.fscrawler] or [/home/mkamal/.fscrawler/legal_test/_mappings]. You should look at the documentation about upgrades: https://github.com/dadoonet/fscrawler#upgrade-to-23
09:44:45,738 INFO  [f.p.e.c.f.FsCrawlerImpl] Starting FS crawler
09:44:45,741 DEBUG [f.p.e.c.f.c.ElasticsearchClientManager] FS crawler connected to an elasticsearch [6.1.2] node.
09:44:45,741 DEBUG [f.p.e.c.f.c.ElasticsearchClient] create index [legal_test]
09:44:45,751 DEBUG [f.p.e.c.f.c.ElasticsearchClient] create index [legal_test_folder]
09:44:46,670 INFO  [f.p.e.c.f.FsCrawlerImpl] FS crawler Rest service started on [http://127.0.0.1:8080/fscrawler]

**Comment by dadoonet** [comment]
And then can you run 

```
curl http://127.0.0.1:8080/fscrawler/
```

And paste the FSCrawler logs (which is still running in debug mode).

**Comment by MoKmaal** [comment]
nothing happened in terminal, it still show the same result 
and it gives me the same error in connection 
 
mkamal@mkamal-Inspiron-5559:~/fscrawler-2.4/bin$ ./fscrawler legal_test --loop 0 --rest --debug
09:50:36,943 DEBUG [f.p.e.c.f.u.FsCrawlerUtil] Mapping [2/_settings.json] already exists
09:50:36,944 DEBUG [f.p.e.c.f.u.FsCrawlerUtil] Mapping [2/_settings_folder.json] already exists
09:50:36,944 DEBUG [f.p.e.c.f.u.FsCrawlerUtil] Mapping [5/_settings.json] already exists
09:50:36,944 DEBUG [f.p.e.c.f.u.FsCrawlerUtil] Mapping [5/_settings_folder.json] already exists
09:50:36,944 DEBUG [f.p.e.c.f.u.FsCrawlerUtil] Mapping [6/_settings.json] already exists
09:50:36,944 DEBUG [f.p.e.c.f.u.FsCrawlerUtil] Mapping [6/_settings_folder.json] already exists
09:50:36,945 DEBUG [f.p.e.c.f.FsCrawler] Starting job [legal_test]...
09:50:37,426 DEBUG [f.p.e.c.f.c.ElasticsearchClient] Using elasticsearch >= 5, so we can use ingest node feature
09:50:37,493 WARN  [f.p.e.c.f.FsCrawler] We found old configuration index settings in [/home/mkamal/.fscrawler] or [/home/mkamal/.fscrawler/legal_test/_mappings]. You should look at the documentation about upgrades: https://github.com/dadoonet/fscrawler#upgrade-to-23
09:50:37,493 INFO  [f.p.e.c.f.FsCrawlerImpl] Starting FS crawler
09:50:37,498 DEBUG [f.p.e.c.f.c.ElasticsearchClientManager] FS crawler connected to an elasticsearch [6.1.2] node.
09:50:37,498 DEBUG [f.p.e.c.f.c.ElasticsearchClient] create index [legal_test]
09:50:37,509 DEBUG [f.p.e.c.f.c.ElasticsearchClient] create index [legal_test_folder]
09:50:38,506 INFO  [f.p.e.c.f.FsCrawlerImpl] FS crawler Rest service started on [http://127.0.0.1:8080/fscrawler]

**Comment by dadoonet** [comment]
So FSCrawler is not reached at all.

My guess is that you have a proxy on your machine which redirects that kind of request apparently.

**Comment by MoKmaal** [comment]
at browser, this is the results
but in terminal gives me connection error
![screenshot from 2018-02-01 09-45-43](https://user-images.githubusercontent.com/18743451/35667306-cfdcb7e8-0735-11e8-8cd1-07461dd2aadf.png)

**Comment by MoKmaal** [comment]
So, if I run it in another machine, would it work?
could I try again and return to ask you, please?

**Comment by dadoonet** [comment]
Sure but I'd check my proxy settings locally. I mean that if you are working in a company you might have corporate proxy settings.

**Comment by dadoonet** [comment]
> at browser, this is the results
> but in terminal gives me connection error

That definitely shows that something looks wrong in your machine settings and that FSCrawler is working fine.

**Comment by shadiakiki1986** [comment]
What if you use 127.0.0.1 in your browser instead if localhost?

Also try curl with localhost instead of 127.0.0.1

**Comment by MoKmaal** [comment]
It works fine when I typed the localhost instead of 12.0.0.1
thanks for your support dudes 
@dadoonet  @shadiakiki1986

**Comment by dadoonet** [comment]
Awesome! Thanks a lot to @shadiakiki1986!

**Comment by DaLiangLee** [comment]
> 太棒了！非常感谢@ shadiakiki1986！

I am running fscrawler on the aws linux server and I get an error when executing 
`curl url:9091/fscrawler/ `
locally.

server:
`name: "job_qmsc"
fs:
  url: "/tmp/es"
  update_rate: "15m"
  excludes:
  - "*/~*"
  json_support: false
  filename_as_id: false
  add_filesize: true
  remove_deleted: true
  add_as_inner_object: false
  store_source: false
  index_content: true
  attributes_support: false
  raw_metadata: false
  xml_support: false
  index_folders: true
  lang_detect: false
  continue_on_error: false
  ocr:
    language: "eng"
    enabled: true
    pdf_strategy: "ocr_and_text"
  follow_symlinks: false
elasticsearch:
  nodes:
  - url: "https://vpc-xxxes.amazonaws.com"
  bulk_size: 100
  flush_interval: "5s"
  byte_size: "10mb"
rest:
  url : "http://127.0.0.1:9091/fscrawler"
  enable_cors: false
~
`
server:
`$ curl http://127.0.0.1:9091/fscrawler/
{"ok":true,"version":"2.7-SNAPSHOT","elasticsearch":"7.1.1","settings":{"name":"job_name","fs":{"url":"/tmp/es","update_rate":"15m","excludes":["*/~*"],"json_support":false,"filename_as_id":false,"add_filesize":true,"remove_deleted":true,"add_as_inner_object":false,"store_source":false,"index_content":true,"attributes_support":false,"raw_metadata":false,"xml_support":false,"index_folders":true,"lang_detect":false,"continue_on_error":false,"ocr":{"language":"eng","enabled":true,"pdf_strategy":"ocr_and_text"},"follow_symlinks":false},"elasticsearch":{"nodes":[{"url":"https://vpc-xxxxus-east-1.es.amazonaws.com"}],"index":"job_name","index_folder":"job_name","bulk_size":100,"flush_interval":"5s","byte_size":"10mb"},"rest":{"url":"http://127.0.0.1:9091/fscrawler","enable_cors":false}}}[developer@ip-172-31-62-74 job_qmsc]$

`

local:
`curl -v 52.x.xxx.106:9091/fscrawler/
*   Trying 52.x.xxx.106...
* TCP_NODELAY set
* connect to 52.x.xxx.106 port 9091 failed: Connection refused
* Failed to connect to 52.x.xxx.106 port 9091: Connection refused
* Closing connection 0
curl: (7) Failed to connect to 52x.xxx.106 port 9091: Connection refused`

What should I do to solve this question, please?

**Comment by dadoonet** [comment]
I wonder if you should not change:

```yml
rest:
  url : "http://127.0.0.1:9091/fscrawler"
```

with

```yml
rest:
  url : "http://52.x.xxx.106:9091/fscrawler"
```

Also, did you check your firewall rules?

**Comment by DaLiangLee** [comment]
> I wonder if you should not change:
> 
> ```yaml
> rest:
>   url : "http://127.0.0.1:9091/fscrawler"
> ```
> 
> with
> 
> ```yaml
> rest:
>   url : "http://52.x.xxx.106:9091/fscrawler"
> ```
> 
> Also, did you check your firewall rules?

**Fatal error received while running the crawler: [Failed to start Grizzly HTTP server: Cannot assign requested address**


`$  bin/fscrawler job_qmsc --loop 0 --rest --debug
08:14:27,857 INFO  [f.p.e.c.f.c.BootstrapChecks] Memory [Free/Total=Percent]: HEAP [42.2mb/880mb=4.8%], RAM [762.2mb                                                                                                                         /3.8gb=19.28%], Swap [0b/0b=0.0].
08:14:27,864 DEBUG [f.p.e.c.f.f.FsCrawlerUtil] Mapping [2/_settings.json] already exists
08:14:27,864 DEBUG [f.p.e.c.f.f.FsCrawlerUtil] Mapping [2/_settings_folder.json] already exists
08:14:27,864 DEBUG [f.p.e.c.f.f.FsCrawlerUtil] Mapping [5/_settings.json] already exists
08:14:27,864 DEBUG [f.p.e.c.f.f.FsCrawlerUtil] Mapping [5/_settings_folder.json] already exists
08:14:27,865 DEBUG [f.p.e.c.f.f.FsCrawlerUtil] Mapping [6/_settings.json] already exists
08:14:27,865 DEBUG [f.p.e.c.f.f.FsCrawlerUtil] Mapping [6/_settings_folder.json] already exists
08:14:27,865 DEBUG [f.p.e.c.f.f.FsCrawlerUtil] Mapping [7/_settings.json] already exists
08:14:27,865 DEBUG [f.p.e.c.f.f.FsCrawlerUtil] Mapping [7/_settings_folder.json] already exists
08:14:27,865 DEBUG [f.p.e.c.f.c.FsCrawlerCli] Starting job [job_qmsc]...
08:14:28,230 DEBUG [f.p.e.c.f.c.ElasticsearchClientUtil] Trying to find a client version 7
08:14:28,873 INFO  [f.p.e.c.f.c.v.ElasticsearchClientV7] Elasticsearch Client for version 7.x connected to a node ru                                                                                                                         nning version 7.1.1
08:14:28,939 INFO  [f.p.e.c.f.FsCrawlerImpl] Starting FS crawler
08:14:28,943 DEBUG [f.p.e.c.f.c.v.ElasticsearchClientV7] FS crawler connected to an elasticsearch [org.elasticsearch                                                                                                                         .client.core.MainResponse$Version@5f6183a1] node.
08:14:28,944 DEBUG [f.p.e.c.f.c.v.ElasticsearchClientV7] create index [job_qmsc]
08:14:29,124 DEBUG [f.p.e.c.f.c.v.ElasticsearchClientV7] wait for yellow health on index [job_qmsc]
08:14:29,143 DEBUG [f.p.e.c.f.c.v.ElasticsearchClientV7] create index [job_qmsc_folder]
08:14:29,154 DEBUG [f.p.e.c.f.c.v.ElasticsearchClientV7] wait for yellow health on index [job_qmsc_folder]
08:14:29,159 DEBUG [f.p.e.c.f.FsParserNoop] Fs crawler is going to sleep for 15m
08:14:29,668 WARN  [o.g.j.i.i.Providers] A provider fr.pilato.elasticsearch.crawler.fs.rest.UploadApi registered in                                                                                                                          SERVER runtime does not implement any provider interfaces applicable in the SERVER runtime. Due to constraint config                                                                                                                         uration problems the provider fr.pilato.elasticsearch.crawler.fs.rest.UploadApi will be ignored.
08:14:29,669 WARN  [o.g.j.i.i.Providers] A provider fr.pilato.elasticsearch.crawler.fs.rest.ServerStatusApi register                                                                                                                         ed in SERVER runtime does not implement any provider interfaces applicable in the SERVER runtime. Due to constraint                                                                                                                          configuration problems the provider fr.pilato.elasticsearch.crawler.fs.rest.ServerStatusApi will be ignored.
08:14:30,070 FATAL [f.p.e.c.f.c.FsCrawlerCli] Fatal error received while running the crawler: [Failed to start Grizz                                                                                                                         ly HTTP server: Cannot assign requested address]
08:14:30,070 DEBUG [f.p.e.c.f.c.FsCrawlerCli] error caught
javax.ws.rs.ProcessingException: Failed to start Grizzly HTTP server: Cannot assign requested address
        at org.glassfish.jersey.grizzly2.httpserver.GrizzlyHttpServerFactory.createHttpServer(GrizzlyHttpServerFacto                                                                                                                         ry.java:270) ~[jersey-container-grizzly2-http-2.29.jar:?]
        at org.glassfish.jersey.grizzly2.httpserver.GrizzlyHttpServerFactory.createHttpServer(GrizzlyHttpServerFacto                                                                                                                         ry.java:93) ~[jersey-container-grizzly2-http-2.29.jar:?]
        at fr.pilato.elasticsearch.crawler.fs.rest.RestServer.start(RestServer.java:61) ~[fscrawler-rest-2.7-SNAPSHO                                                                                                                         T.jar:?]
        at fr.pilato.elasticsearch.crawler.fs.cli.FsCrawlerCli.main(FsCrawlerCli.java:274) [fscrawler-cli-2.7-SNAPSH                                                                                                                         OT.jar:?]
Caused by: java.net.BindException: Cannot assign requested address
`

When I changed to rest:
   I encountered this error when` url : "http://52.x.xxx.106:9091/fscrawler".`

In addition, I would like to ask if fscrawler supports dynamic paths, for example, I tell him a path, then he goes to read the file.

**Comment by DaLiangLee** [comment]
@dadoonet 
Just your answer has helped, and I have another question:
I would like to ask if fscrawler supports dynamic paths, for example, I tell him a path, then he goes to read the file.

**Comment by dadoonet** [comment]
@DaLiangLee For the future readers, could you tell what you exactly fixed?

**Comment by DaLiangLee** [comment]
> @DaLiangLee对于未来的读者，您能告诉您确切的内容吗？

In AWS LINUX, the 9091 port I used is not open by default. In addition, the IP address has a public network and an internal network. The internal network IP needs to be used on the server.

Whether it's linux or windows, fscrawler is in `bin / fscrawler job_name`
willgenerate two _setting.yaml, you need to find the files under the .fscrawler folder

**Comment by DaLiangLee** [comment]
> @DaLiangLee For the future readers, could you tell what you exactly fixed?

1. Does fscrawler limit the file size, such as a 200MB PDF, is indexed_chars a relevant setting? In addition, does Elasticsearch limit the files accepted by fscrawler, if the files processed by fscrawler are relatively large
2. 
`bin \ fscrawler job_name --loop 0 --rest` I just want to use curl to send the file to fscrawler for elasticsearch. I don't want to use folder detection. Is this correct?

3.I am using putty to connect to the server to start the service, but when the terminal window is closed, the service is stopped. Can I keep the fscrawler running?

thank you very much for your help.

**Comment by dadoonet** [comment]
Hi @DaLiangLee. Your questions are unrelated to the original discussion. It'd be better to move them somewhere else. Like on https://discuss.elastic.co/c/elasticsearch

**Comment by dminovski0** [comment]
@DaLiangLee 

For 3. using Putty and keeping the service running after closing. After logging with Putty, maybe you will need root access with
`sudo -i`.
 Use the command
`tmux`
to enter its screen and start FScrawler from there. After starting the FScrawler, try to detach with
`tmux detach`
or
`Ctrl+B` and then `Ctrl+D`.
If that doesn't work close the session, FScrawler will keep running.
You can enter tmux again in another session, to reset it and stop the processes use the command:
`tmux kill-server`.

References:
https://www.tecmint.com/keep-remote-ssh-sessions-running-after-disconnection/
https://stackoverflow.com/questions/38295615/complete-tmux-reset
