### ISSUE TITLE
Don't send text-based PDFs to tesseract

### ISSUE THREAD

**Issue by budachst** [dadoonet/fscrawler#628]
It seems that setting "pdf_ocr" : true will send every PDF to tesseract, even if it's a text based PDF where the text can be easily extracted without using tesseract.  Isn't there a method in place which checks, if the PDF that is about to be indexed, needs to be OCR'ed?

This causes a 24 page text PDF to run for 6 mins. through tesseract, which will also reduce the accurarcy of the index, since tesseract can only be less accurate than the text inside the PDF.

**Comment by dadoonet** [comment]
@tballison Do you know if this option exists in Tika?
I can otherwise have 2 impl of the Tika instance, one with OCR and one without.

Then I can send documents to Tika without OCR and if I'm getting an empty content for DOCs, PDF, ... I can send them to the Tika instance with OCR... 
That might slow down the process in case of many documents with images although I can add a "force_ocr" option, but that can certainly be a big win in case of a few of them...

@budachst Thoughts?

**Comment by budachst** [comment]
Well… I can't judge the additional overhead for trying to check PDFs without OCS first, but given the fact, that rendering/OCR'ing a multipage document costs minutes, I'd reckon that trying a simple PDF2TEXT (if that is somewhere available in the toolset/libraries) might pay-off very well. If I set "pdf_ocr": false, fscrawler just flies through the documents…

However… it always depends on the dataset, of course. I do like the idea of two switches, where

pdf_ocr : true -> perfoms OCR on PDFs only if the prior try to extract text from the PDF fails
force_ocr: true -> always performs OCR on PDFs, in case there  are PDFs, where there is actual content in the graphics worth indexing

My guess would be, that the majority will just be fine with the first option

**Comment by tballison** [comment]
Sorry for my delay.

First, generally we have an open ticket to improve OCR of PDFs:
https://issues.apache.org/jira/plugins/servlet/mobile#issue/TIKA-2749/

When I have time to work on that... :(

My sense is that it will be better to handle the OCR question per page
rather than per document but that’d be Tika’s responsibility, not yours!
Your proposal sounds reasonable.

See:
https://wiki.apache.org/tika/TikaOCR and
https://wiki.apache.org/tika/PDFParser%20%28Apache%20PDFBox%29

Let me know if you have any questions.

**Comment by dadoonet** [comment]
I realize that this has been fixed in 2.7 and documented with #965.
