### ISSUE TITLE
New files in folder are detected like an indexing

### ISSUE THREAD

**Issue by MaxJust** [dadoonet/fscrawler#93]
HI, when i put new file in the folder I got this message in the logs:
[2014-10-29 14:35:43,221][DEBUG][fr.pilato.elasticsearch.river.fs.river.FsRiver] [Ninja] [fs][testriver]     - not modified: creation date 1414581801000 , file date 1414581801000, last scan date 1414582486000

But then I use this command: touch filename.pdf, fsriver index them. what wrong?

PS it is a absolutly new file,  i check it twice.

**Comment by dadoonet** [comment]
Can you try it again with fscrawler 2.0.0 which has just been released?

May be you moved a file from a dir to another? In that case the file system does not really change the date I guess.
So touching the file is the only thing you can do.

If you copy the file instead of moving it, it might work better?
